# Generated by Django 2.2.28 on 2023-03-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_praise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='User',
        ),
    ]
