# Generated by Django 2.2.28 on 2023-03-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_searchquery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
