# Generated by Django 2.2.28 on 2023-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230317_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images'),
        ),
    ]
