# Generated by Django 2.2.28 on 2023-03-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_picture',
        ),
    ]
